// apps/native/src/components/DatePicker.tsx
import React, { useMemo, useState } from 'react';
import { Modal, Pressable, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { MONTHS, WEEKDAYS, formatDate, monthGrid, parseIsoDate, toIsoDate } from '@chatlol/shared';
import { haptic } from '../lib/native';
import { gradients, shadow, useColors } from '../lib/theme';
import { Gradient, Icon, IconButton, Row, Tap, Text } from './ui';

type View3 = 'days' | 'months' | 'years';

/**
 * Sunset-styled date picker in a bottom sheet: pick a year, a month, then a day.
 * `startView="years"` suits birthdays. Works the same on iOS, Android and the web/desktop build.
 */
export function DatePicker({ value, onChange, min = '1900-01-01', max, placeholder = 'Pick a date', startView = 'days', defaultYear, label }: {
  value: string; onChange: (iso: string) => void; min?: string; max?: string; placeholder?: string; startView?: View3; defaultYear?: number; label?: string;
}) {
  const c = useColors();
  const insets = useSafeAreaInsets();
  const today = new Date().toISOString().slice(0, 10);
  const maxIso = max ?? '9999-12-31';
  const [open, setOpen] = useState(false);
  const [view, setView] = useState<View3>(startView);
  const initial = () => parseIsoDate(value) ?? { y: defaultYear ?? Number(today.slice(0, 4)), m: Number(today.slice(5, 7)) - 1, d: 1 };
  const [cur, setCur] = useState(initial);
  const minY = Number(min.slice(0, 4));
  const maxY = Number(maxIso.slice(0, 4));
  const pageStart = cur.y - (cur.y % 20);
  const cells = useMemo(() => monthGrid(cur.y, cur.m), [cur.y, cur.m]);
  const selected = parseIsoDate(value);

  function show() { setCur(initial()); setView(value ? 'days' : startView); setOpen(true); }
  function shift(delta: number) {
    haptic.tap();
    if (view === 'years') setCur({ ...cur, y: cur.y + delta * 20 });
    else if (view === 'months') setCur({ ...cur, y: cur.y + delta });
    else { const d = new Date(Date.UTC(cur.y, cur.m + delta, 1)); setCur({ y: d.getUTCFullYear(), m: d.getUTCMonth(), d: 1 }); }
  }
  const canPrev = view === 'years' ? pageStart > minY : view === 'months' ? cur.y > minY : toIsoDate(cur.y, cur.m, 1) > min;
  const canNext = view === 'years' ? pageStart + 19 < maxY : view === 'months' ? cur.y < maxY : toIsoDate(cur.y, cur.m + 1, 1) <= maxIso;
  const off = (iso: string) => iso < min || iso > maxIso;

  const pill = (active: boolean, disabled: boolean) => ({
    height: 46, borderRadius: 23, alignItems: 'center' as const, justifyContent: 'center' as const, opacity: disabled ? 0.3 : 1,
    backgroundColor: active ? c.flame : 'transparent',
  });

  return (
    <>
      <Tap onPress={show} accessibilityRole="button" accessibilityLabel={label ?? placeholder}
        style={{ minHeight: 52, borderRadius: 999, borderWidth: 1, borderColor: open ? c.flame : c.sandstone, backgroundColor: c.surfaceContainerLowest, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', gap: 10 }}>
        <Icon name="calendar-month" color={c.flame} />
        <Text variant="bodyLg" color={value ? c.onSurface : c.outline} style={{ flex: 1 }}>{value ? formatDate(value) : placeholder}</Text>
        <Icon name="expand-more" />
      </Tap>
      <Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}>
        <Pressable style={{ flex: 1, backgroundColor: 'rgba(26,17,12,0.55)' }} onPress={() => setOpen(false)} accessibilityLabel="Close date picker" />
        <View style={[{ backgroundColor: c.surfaceContainerLowest, borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 18, paddingBottom: insets.bottom + 18, gap: 12 }, shadow.float]}>
          <Row>
            <Text variant="headlineMd" style={{ flex: 1 }}>{label ?? 'Pick a date'}</Text>
            {value ? <Text variant="labelLg" color={c.flame}>{formatDate(value)}</Text> : null}
          </Row>
          <Row gap={6}>
            <IconButton name="chevron-left" label="Previous" onPress={canPrev ? () => shift(-1) : undefined} color={canPrev ? c.onSurface : c.outlineVariant} />
            <Tap onPress={() => setView(view === 'days' ? 'months' : 'years')} style={{ flex: 1, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: c.surfaceContainerLow }}>
              <Text variant="labelLg">{view === 'days' ? `${MONTHS[cur.m]} ${cur.y}` : view === 'months' ? String(cur.y) : `${pageStart} – ${pageStart + 19}`}</Text>
            </Tap>
            <IconButton name="chevron-right" label="Next" onPress={canNext ? () => shift(1) : undefined} color={canNext ? c.onSurface : c.outlineVariant} />
          </Row>

          {view === 'years' ? (
            <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
              {Array.from({ length: 20 }, (_, i) => pageStart + i).map((y) => {
                const dis = y < minY || y > maxY;
                return (
                  <View key={y} style={{ width: '25%', padding: 3 }}>
                    <Tap disabled={dis} onPress={() => { haptic.tap(); setCur({ ...cur, y }); setView('months'); }} style={pill(selected?.y === y, dis)}>
                      <Text variant="labelLg" color={selected?.y === y ? '#fff' : c.onSurface}>{y}</Text>
                    </Tap>
                  </View>
                );
              })}
            </View>
          ) : view === 'months' ? (
            <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
              {MONTHS.map((name, m) => {
                const dis = toIsoDate(cur.y, m, 1) > maxIso || toIsoDate(cur.y, m + 1, 0) < min;
                const active = selected?.y === cur.y && selected.m === m;
                return (
                  <View key={name} style={{ width: '33.33%', padding: 3 }}>
                    <Tap disabled={dis} onPress={() => { haptic.tap(); setCur({ ...cur, m }); setView('days'); }} style={pill(active, dis)}>
                      <Text variant="labelLg" color={active ? '#fff' : c.onSurface}>{name.slice(0, 3)}</Text>
                    </Tap>
                  </View>
                );
              })}
            </View>
          ) : (
            <View>
              <View style={{ flexDirection: 'row' }}>{WEEKDAYS.map((w) => <Text key={w} variant="labelSm" color={c.onSurfaceVariant} style={{ width: '14.28%', textAlign: 'center', paddingVertical: 4 }}>{w}</Text>)}</View>
              <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
                {cells.map((cell) => {
                  const dis = off(cell.iso);
                  const active = cell.iso === value;
                  return (
                    <View key={cell.iso} style={{ width: '14.28%', aspectRatio: 1, padding: 2 }}>
                      <Tap disabled={dis} accessibilityLabel={formatDate(cell.iso)} accessibilityState={{ selected: active, disabled: dis }}
                        onPress={() => { haptic.success(); onChange(cell.iso); setOpen(false); }}
                        style={{ flex: 1, borderRadius: 999, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', opacity: dis ? 0.25 : 1, borderWidth: cell.iso === today && !active ? 1 : 0, borderColor: c.flame }}>
                        {active ? <Gradient colors={gradients.sunset} style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }} /> : null}
                        <Text variant="labelLg" color={active ? '#fff' : cell.inMonth ? c.onSurface : c.outline}>{cell.d}</Text>
                      </Tap>
                    </View>
                  );
                })}
              </View>
            </View>
          )}
          <Row style={{ justifyContent: 'space-between' }}>
            <Text variant="labelMd" color={c.onSurfaceVariant} onPress={() => setView('years')}>Jump to year</Text>
            <Text variant="labelMd" color={c.flame} onPress={() => setOpen(false)}>{value ? 'Done' : 'Cancel'}</Text>
          </Row>
        </View>
      </Modal>
    </>
  );
}

// apps/web/src/components/DatePicker.vue
<script setup lang="ts">
import { computed, nextTick, onUnmounted, ref, watch } from 'vue';
import { MONTHS, WEEKDAYS, formatDate, monthGrid, parseIsoDate, toIsoDate } from '@chatlol/shared';
import Icon from './Icon.vue';

/**
 * Sunset-styled date picker: tap the field, pick a year, a month, then a day.
 * `startView="years"` suits birthdays (jump decades instead of clicking back month by month).
 */
const props = withDefaults(
  defineProps<{ modelValue: string; min?: string; max?: string; placeholder?: string; startView?: 'days' | 'months' | 'years'; defaultYear?: number; label?: string }>(),
  { min: '1900-01-01', placeholder: 'Pick a date', startView: 'days' },
);
const emit = defineEmits<{ (e: 'update:modelValue', v: string): void }>();
const open = ref(false);
const view = ref<'days' | 'months' | 'years'>(props.startView);
const today = new Date().toISOString().slice(0, 10);
const maxIso = computed(() => props.max ?? '9999-12-31');
const initial = () => parseIsoDate(props.modelValue) ?? { y: props.defaultYear ?? Number(today.slice(0, 4)), m: Number(today.slice(5, 7)) - 1, d: 1 };
const cursor = ref(initial());
const root = ref<HTMLElement>();
const grid = ref<HTMLElement>();

const yearPageStart = computed(() => cursor.value.y - (cursor.value.y % 20));
const years = computed(() => Array.from({ length: 20 }, (_, i) => yearPageStart.value + i));
const cells = computed(() => monthGrid(cursor.value.y, cursor.value.m));
const minY = computed(() => Number(props.min.slice(0, 4)));
const maxY = computed(() => Number(maxIso.value.slice(0, 4)));
const disabledIso = (iso: string) => iso < props.min || iso > maxIso.value;
const monthDisabled = (m: number) => toIsoDate(cursor.value.y, m, 1) > maxIso.value || toIsoDate(cursor.value.y, m + 1, 0) < props.min;

function toggle() {
  open.value = !open.value;
  if (open.value) {
    cursor.value = initial();
    view.value = props.modelValue ? 'days' : props.startView;
  }
}
function pickYear(y: number) { cursor.value = { ...cursor.value, y }; view.value = 'months'; }
function pickMonth(m: number) { cursor.value = { ...cursor.value, m }; view.value = 'days'; }
function pickDay(iso: string) {
  if (disabledIso(iso)) return;
  emit('update:modelValue', iso);
  open.value = false;
}
function shift(delta: number) {
  if (view.value === 'years') cursor.value = { ...cursor.value, y: cursor.value.y + delta * 20 };
  else if (view.value === 'months') cursor.value = { ...cursor.value, y: cursor.value.y + delta };
  else {
    const d = new Date(Date.UTC(cursor.value.y, cursor.value.m + delta, 1));
    cursor.value = { y: d.getUTCFullYear(), m: d.getUTCMonth(), d: 1 };
  }
}
const canPrev = computed(() => (view.value === 'years' ? yearPageStart.value > minY.value : view.value === 'months' ? cursor.value.y > minY.value : toIsoDate(cursor.value.y, cursor.value.m, 1) > props.min));
const canNext = computed(() => (view.value === 'years' ? yearPageStart.value + 19 < maxY.value : view.value === 'months' ? cursor.value.y < maxY.value : toIsoDate(cursor.value.y, cursor.value.m + 1, 1) <= maxIso.value));

// Keyboard: arrows move the selected day, Enter picks, Escape closes.
function onKey(e: KeyboardEvent) {
  if (e.key === 'Escape') return (open.value = false);
  if (view.value !== 'days') return;
  const step = { ArrowLeft: -1, ArrowRight: 1, ArrowUp: -7, ArrowDown: 7 }[e.key];
  if (step) {
    e.preventDefault();
    const d = new Date(Date.UTC(cursor.value.y, cursor.value.m, cursor.value.d + step));
    cursor.value = { y: d.getUTCFullYear(), m: d.getUTCMonth(), d: d.getUTCDate() };
    void nextTick(() => (grid.value?.querySelector('[data-focus="true"]') as HTMLElement | null)?.focus());
  } else if (e.key === 'Enter') {
    e.preventDefault();
    pickDay(toIsoDate(cursor.value.y, cursor.value.m, cursor.value.d));
  }
}
const onDoc = (e: MouseEvent) => { if (open.value && root.value && !root.value.contains(e.target as Node)) open.value = false; };
watch(open, (o) => (o ? document.addEventListener('mousedown', onDoc) : document.removeEventListener('mousedown', onDoc)));
onUnmounted(() => document.removeEventListener('mousedown', onDoc));
</script>

<template>
  <div ref="root" class="relative" @keydown="onKey">
    <button type="button" class="input flex items-center gap-3 text-left" :class="{ 'border-flame ring-2 ring-flame/20': open }" :aria-label="label ?? placeholder" aria-haspopup="dialog" :aria-expanded="open" @click="toggle">
      <Icon name="calendar_month" class="text-flame" />
      <span :class="modelValue ? 'text-on-surface' : 'text-outline'">{{ modelValue ? formatDate(modelValue) : placeholder }}</span>
      <Icon name="expand_more" class="ml-auto text-on-surface-variant transition" :class="{ 'rotate-180': open }" />
    </button>
    <Transition name="fade">
      <div v-if="open" role="dialog" :aria-label="label ?? 'Choose a date'" class="absolute z-50 mt-2 w-full min-w-[300px] max-w-[380px] card shadow-float p-4 animate-pop">
        <div class="flex items-center gap-2 mb-3">
          <button type="button" class="btn-icon w-9 h-9" :disabled="!canPrev" aria-label="Previous" @click="shift(-1)"><Icon name="chevron_left" /></button>
          <button v-if="view === 'days'" type="button" class="flex-1 h-9 rounded-full text-label-lg hover:bg-surface-container-low" @click="view = 'months'">{{ MONTHS[cursor.m] }} {{ cursor.y }}</button>
          <button v-else-if="view === 'months'" type="button" class="flex-1 h-9 rounded-full text-label-lg hover:bg-surface-container-low" @click="view = 'years'">{{ cursor.y }}</button>
          <span v-else class="flex-1 text-center text-label-lg">{{ years[0] }} – {{ years[19] }}</span>
          <button type="button" class="btn-icon w-9 h-9" :disabled="!canNext" aria-label="Next" @click="shift(1)"><Icon name="chevron_right" /></button>
        </div>

        <div v-if="view === 'years'" class="grid grid-cols-4 gap-1.5">
          <button v-for="y in years" :key="y" type="button" :disabled="y < minY || y > maxY" class="h-11 rounded-full text-label-lg transition disabled:opacity-30"
            :class="y === (parseIsoDate(modelValue)?.y ?? -1) ? 'bg-sunset text-white shadow-glow' : 'hover:bg-sunlit'" @click="pickYear(y)">{{ y }}</button>
        </div>

        <div v-else-if="view === 'months'" class="grid grid-cols-3 gap-1.5">
          <button v-for="(name, m) in MONTHS" :key="name" type="button" :disabled="monthDisabled(m)" class="h-12 rounded-full text-label-lg transition disabled:opacity-30"
            :class="m === cursor.m && cursor.y === parseIsoDate(modelValue)?.y ? 'bg-sunset text-white shadow-glow' : 'hover:bg-sunlit'" @click="pickMonth(m)">{{ name.slice(0, 3) }}</button>
        </div>

        <template v-else>
          <div class="grid grid-cols-7 text-center label mb-1"><span v-for="w in WEEKDAYS" :key="w" class="py-1">{{ w }}</span></div>
          <div ref="grid" class="grid grid-cols-7 gap-0.5" role="grid">
            <button v-for="c in cells" :key="c.iso" type="button" role="gridcell" :disabled="disabledIso(c.iso)" :aria-selected="c.iso === modelValue" :aria-label="formatDate(c.iso)"
              :data-focus="c.y === cursor.y && c.m === cursor.m && c.d === cursor.d" :tabindex="c.y === cursor.y && c.m === cursor.m && c.d === cursor.d ? 0 : -1"
              class="aspect-square rounded-full text-body-md font-bold transition disabled:opacity-25 focus:outline-none focus:ring-2 focus:ring-flame/40"
              :class="[c.iso === modelValue ? 'bg-sunset text-white shadow-glow' : c.iso === today ? 'ring-1 ring-flame text-flame' : 'hover:bg-sunlit', !c.inMonth && c.iso !== modelValue ? 'text-outline/60' : '']"
              @click="pickDay(c.iso)">{{ c.d }}</button>
          </div>
        </template>
        <div class="flex justify-between mt-3 text-label-md">
          <button type="button" class="text-on-surface-variant hover:text-primary" @click="view = 'years'">Jump to year</button>
          <button v-if="modelValue" type="button" class="text-primary" @click="open = false">Done</button>
        </div>
      </div>
    </Transition>
  </div>
</template>
