// apps/native/src/components/ProfileSong.tsx
import React from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';
import type { ProfileSong as Song } from '@chatlol/shared';


/**
 * A member's profile song in Spotify's embedded player. With `autoplay` the page starts it as soon as it loads
 * (allowed in-app because media playback doesn't wait for a tap). Spotify plays a preview unless the
 * viewer is signed in to Spotify.
 */
export function ProfileSong({ song, autoplay }: { song: Song; autoplay?: boolean }) {
  if (song.source === 'apple') return <ApplePreview song={song} autoplay={autoplay} />;
  const uri = `spotify:${song.type}:${song.id}`;
  const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;background:transparent}</style></head>
<body><div id="p"></div><script src="https://open.spotify.com/embed/iframe-api/v1" async></script>
<script>window.onSpotifyIframeApiReady=function(api){api.createController(document.getElementById('p'),{uri:${JSON.stringify(uri)},height:80,width:'100%'},function(c){${autoplay ? "c.addListener('ready',function(){c.play()});" : ''}});};</script></body></html>`;
  return (
    <View style={{ height: 80, borderRadius: 14, overflow: 'hidden' }}>
      <WebView
        source={{ html, baseUrl: 'https://open.spotify.com' }}
        originWhitelist={['*']}
        mediaPlaybackRequiresUserAction={false}
        allowsInlineMediaPlayback
        scrollEnabled={false}
        style={{ backgroundColor: 'transparent' }}
        // Fallback when the iFrame API can't load: the plain embed still works.
        onError={() => undefined}
        accessibilityLabel={`Profile song${song.title ? `: ${song.title}` : ''}`}
      />
    </View>
  );
}

const esc = (t: string) => t.replace(/[&<>"']/g, (ch) => `&#${ch.charCodeAt(0)};`);

/** Apple Music 30-second preview (used when the server has no Spotify keys), in a small player page. */
function ApplePreview({ song, autoplay }: { song: Song; autoplay?: boolean }) {
  const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
html,body{margin:0;background:#1c1c1e;color:#fff;font-family:-apple-system,system-ui,sans-serif}
.w{display:flex;align-items:center;gap:10px;padding:10px}img{width:56px;height:56px;border-radius:6px;object-fit:cover}
.t{flex:1;min-width:0}.n{font-weight:700;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.a{opacity:.7;font-size:12px}
.bar{height:5px;border-radius:3px;background:rgba(255,255,255,.2);margin-top:8px}.f{height:100%;width:0;border-radius:3px;background:#fa2d48}
button{width:42px;height:42px;border-radius:21px;border:0;background:#fff;font-size:18px}</style></head><body>
<div class="w">${song.artUrl ? `<img src="${esc(song.artUrl)}">` : ''}<div class="t"><div class="n">${esc(song.title || 'Profile song')}</div><div class="a">${esc(song.artist)} · Preview</div><div class="bar"><div class="f" id="f"></div></div></div><button id="b">▶</button></div>
<audio id="au" src="${esc(song.previewUrl ?? '')}" loop ${autoplay ? 'autoplay' : ''}></audio>
<script>var a=document.getElementById('au'),b=document.getElementById('b'),f=document.getElementById('f');
b.onclick=function(){a.paused?a.play():a.pause()};a.onplay=function(){b.textContent='❚❚'};a.onpause=function(){b.textContent='▶'};
a.ontimeupdate=function(){f.style.width=(a.duration?a.currentTime/a.duration*100:0)+'%'};</script></body></html>`;
  return (
    <View style={{ height: 76, borderRadius: 14, overflow: 'hidden' }}>
      <WebView source={{ html }} originWhitelist={['*']} mediaPlaybackRequiresUserAction={false} allowsInlineMediaPlayback scrollEnabled={false} style={{ backgroundColor: '#1c1c1e' }} accessibilityLabel={`Profile song${song.title ? `: ${song.title}` : ''}`} />
    </View>
  );
}

// apps/web/src/components/ProfileSong.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue';
import type { ProfileSong } from '@chatlol/shared';
import { spotifyOpenUrl } from '@chatlol/shared';
import Icon from './Icon.vue';

/**
 * A member's profile song.
 *  - Spotify songs play in Spotify's embed (iFrame API).
 *  - Apple Music songs (used when the server has no Spotify keys) play their 30-second preview in our own player.
 * It starts automatically when the visitor allows it (Settings → "Autoplay profile songs"). Browsers only allow
 * sound after the visitor has interacted with the site — arriving by clicking a link counts — so if a browser
 * still blocks it, the player shows a play button instead.
 */
const props = defineProps<{ song: ProfileSong; autoplay?: boolean }>();
const host = ref<HTMLElement>();
const audio = ref<HTMLAudioElement>();
const playing = ref(false);
const blocked = ref(false);
const progress = ref(0);
const isApple = () => props.song.source === 'apple';
let controller: { play: () => void; pause: () => void; destroy: () => void; loadUri: (u: string) => void; addListener: (e: string, fn: (ev: { data: { isPaused: boolean } }) => void) => void } | null = null;

type IFrameAPI = { createController: (el: HTMLElement, o: object, cb: (c: NonNullable<typeof controller>) => void) => void };
const w = window as unknown as { onSpotifyIframeApiReady?: (api: IFrameAPI) => void; __spotifyApi?: Promise<IFrameAPI> };

function loadApi(): Promise<IFrameAPI> {
  w.__spotifyApi ??= new Promise((resolve) => {
    w.onSpotifyIframeApiReady = resolve;
    const sc = document.createElement('script');
    sc.src = 'https://open.spotify.com/embed/iframe-api/v1';
    sc.async = true;
    document.head.appendChild(sc);
  });
  return w.__spotifyApi;
}

async function mountSpotify() {
  const api = await loadApi();
  if (!host.value) return;
  const el = document.createElement('div');
  host.value.replaceChildren(el);
  api.createController(el, { uri: `spotify:${props.song.type}:${props.song.id}`, height: 80, width: '100%' }, (c) => {
    controller = c;
    c.addListener('playback_update', (e) => (playing.value = !e.data.isPaused));
    c.addListener('ready', () => {
      if (!props.autoplay) return;
      c.play();
      // If nothing is playing shortly after, the browser blocked autoplay: offer a button.
      setTimeout(() => (blocked.value = !playing.value), 2500);
    });
  });
}
async function mountApple() {
  if (!props.autoplay || !audio.value) return;
  try { await audio.value.play(); } catch { blocked.value = true; }
}
function mount() {
  blocked.value = false;
  playing.value = false;
  controller?.destroy();
  controller = null;
  if (isApple()) void mountApple();
  else void mountSpotify();
}
onMounted(mount);
watch(() => props.song.id, mount);
onUnmounted(() => { controller?.destroy(); audio.value?.pause(); });
function play() {
  blocked.value = false;
  if (isApple()) void audio.value?.play().catch(() => (blocked.value = true));
  else controller?.play();
}
function toggle() {
  if (!audio.value) return;
  if (audio.value.paused) play();
  else audio.value.pause();
}
function seek(e: MouseEvent) {
  const a = audio.value;
  if (!a?.duration) return;
  const r = (e.currentTarget as HTMLElement).getBoundingClientRect();
  a.currentTime = ((e.clientX - r.left) / r.width) * a.duration;
}
</script>

<template>
  <div class="rounded-md overflow-hidden relative bg-black/20">
    <template v-if="song.source === 'apple'">
      <div class="flex items-center gap-3 p-2.5 bg-[#1c1c1e] text-white">
        <img v-if="song.artUrl" :src="song.artUrl" alt="" class="w-14 h-14 rounded object-cover shrink-0" />
        <div v-else class="w-14 h-14 rounded bg-white/10 flex items-center justify-center shrink-0"><Icon name="music_note" /></div>
        <div class="min-w-0 flex-1">
          <p class="text-label-lg truncate">{{ song.title || 'Profile song' }}</p>
          <p class="text-body-sm opacity-70 truncate">{{ song.artist }}</p>
          <div class="mt-2 h-1.5 rounded-full bg-white/20 cursor-pointer" @click="seek"><div class="h-full rounded-full bg-[#fa2d48]" :style="{ width: `${progress * 100}%` }" /></div>
        </div>
        <button class="w-11 h-11 rounded-full bg-white text-black flex items-center justify-center shrink-0" :aria-label="playing ? 'Pause' : 'Play'" @click="toggle"><Icon :name="playing ? 'pause' : 'play_arrow'" fill /></button>
      </div>
      <p class="px-3 py-1 text-[11px] bg-[#1c1c1e] text-white/60 flex justify-between"><span>Preview</span><a v-if="song.linkUrl" :href="song.linkUrl" target="_blank" rel="noopener" class="hover:text-white">Listen on Apple Music ↗</a></p>
      <audio ref="audio" :src="song.previewUrl ?? undefined" preload="none" loop @play="playing = true" @pause="playing = false" @timeupdate="progress = audio?.duration ? audio.currentTime / audio.duration : 0" />
    </template>
    <div v-else ref="host" class="min-h-[80px]" />
    <button v-if="blocked" class="absolute inset-0 bg-black/55 text-white flex items-center justify-center gap-2 text-label-lg backdrop-blur-sm" @click="play">
      <Icon name="play_circle" fill /> Play {{ song.title || 'their song' }}
    </button>
    <a v-if="song.source !== 'apple'" :href="spotifyOpenUrl(song)" target="_blank" rel="noopener" class="sr-only">Open in Spotify</a>
  </div>
</template>
