// apps/native/src/components/Someone.tsx
import React from 'react';
import { View } from 'react-native';
import { Image } from 'expo-image';
import { router } from 'expo-router';
import type { UserPublic } from '@chatlol/shared';
import { useColors } from '../lib/theme';
import { Avatar } from './people';
import { Tap, Text } from './ui';

/** A person — or, without Premium, "Someone" with a blurred stranger photo. */
export function Someone({ user, teaser, size = 44 }: { user: UserPublic | null; teaser: string | null; size?: number }) {
  const c = useColors();
  if (user)
    return (
      <Tap onPress={() => router.push(`/u/${user.handle}`)} style={{ flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 }}>
        <Avatar user={user} size={size} />
        <View style={{ flex: 1 }}><Text variant="labelLg" numberOfLines={1}>{user.displayName}</Text><Text variant="bodySm" color={c.onSurfaceVariant}>@{user.handle}</Text></View>
      </Tap>
    );
  return (
    <Tap onPress={() => router.push('/premium')} style={{ flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 }} accessibilityLabel="Someone — unlock with Premium">
      <View style={{ width: size, height: size, borderRadius: size / 2, overflow: 'hidden' }}><Image source={teaser ?? undefined} style={{ width: size, height: size }} blurRadius={12} contentFit="cover" /></View>
      <View style={{ flex: 1 }}><Text variant="labelLg">Someone</Text><Text variant="bodySm" color={c.flame}>👑 Unlock with Premium</Text></View>
    </Tap>
  );
}

// apps/web/src/components/Someone.vue
<script setup lang="ts">
import type { UserPublic } from '@chatlol/shared';
import Avatar from './Avatar.vue';
/** A person, or — without Premium — "Someone" with a blurred stranger photo. */
defineProps<{ user: UserPublic | null; teaser: string | null; size?: number }>();
</script>
<template>
  <RouterLink v-if="user" :to="`/u/${user.handle}`" class="flex items-center gap-3 min-w-0">
    <Avatar :user="user" :size="size ?? 44" /><span class="min-w-0"><span class="text-label-lg block truncate">{{ user.displayName }}</span><span class="text-body-sm text-on-surface-variant truncate">@{{ user.handle }}</span></span>
  </RouterLink>
  <RouterLink v-else to="/premium" class="flex items-center gap-3 min-w-0" title="Unlock with Premium">
    <span class="rounded-full overflow-hidden shrink-0" :style="{ width: (size ?? 44) + 'px', height: (size ?? 44) + 'px' }"><img :src="teaser ?? ''" alt="" class="w-full h-full object-cover blur-[7px] scale-125" /></span>
    <span><span class="text-label-lg block">Someone</span><span class="text-body-sm text-flame">👑 Unlock with Premium</span></span>
  </RouterLink>
</template>
